import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React from "react";
import {AnimatePresence} from "framer-motion";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AnimatePresence mode="wait">
          <Navbar/>
          {children}
        </AnimatePresence>
      </body>
    </html>
  );
}